[[redirects]]
    from = "https://todo-app.felixmohrmann.com/api/todo/*"
    to = "https://todo.felixmohrmann.com/api/todo/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}
